export const actionLabels: Record<string, string> = {
  apply_account_priority_rule: "应用账号优先级规则",
  apply_account_pool_policy: "执行统一账号池策略",
  auto_account_priority_rule: "自动应用账号优先级规则",
  auto_account_balance_webhook_alert: "自动账号余额预警",
  save_account_priority_rule: "保存账号优先级规则",
  save_account_pool_policy: "保存统一账号池策略",
  save_account_balance_webhook: "保存账号余额 Webhook",
  auto_announcement_rule: "自动公告规则",
  auto_bl_apply_bound_rules_after_collection: "采集后应用倍率规则",
  auto_bl_bound_account_rule: "自动应用账号倍率规则",
  auto_bl_bound_group_rule: "自动应用分组倍率规则",
  auto_bl_sync_connection: "自动同步连接",
  auto_bl_sync_group_rate: "自动同步分组倍率",
  apply_bl_account_rate_rule: "应用账号倍率规则",
  apply_bl_group_rate_rule: "应用分组倍率规则",
  bl_sync_group_rate: "手动同步采集倍率",
  clear_error: "清除账号错误",
  cleanup_invalid_data: "清理无效数据",
  clear_user_rate_multipliers: "清空用户倍率",
  create_account: "创建账号",
  create_announcement: "创建公告",
  create_announcement_rule: "创建公告规则",
  create_group: "创建分组",
  delete_account: "删除账号",
  delete_announcement: "删除公告",
  delete_announcement_rule: "删除公告规则",
  delete_group: "删除分组",
  manual_group_rate_update: "手动更新分组倍率",
  manual_group_update: "手动更新分组",
  manual_account_balance_webhook_alert: "手动账号余额预警",
  preview: "预览公告规则",
  refresh_account: "刷新账号凭证",
  save_bl_account_rate_rule: "保存账号倍率规则",
  save_bl_group_rate_rule: "保存分组倍率规则",
  save_bl_source_bindings: "保存采集源绑定",
  set_schedulable: "切换账号调度",
  set_user_rate_multipliers: "设置用户倍率",
  test_account: "测试账号",
  test_account_balance_webhook: "测试账号余额 Webhook",
  update_account: "更新账号",
  update_account_groups: "更新账号分组",
  update_announcement: "更新公告",
  update_announcement_rule: "更新公告规则",
  update_group: "更新分组",
  update_group_rate_multiplier: "更新分组倍率",
  update_site_settings: "更新站点设置",
  upstream_monitor_check: "上游账号检测",
  upstream_monitor_connection: "上游检测连接",
  upstream_monitor_exclude_group_rate_sources: "上游监测排除分组倍率源",
  upstream_monitor_pause_account: "暂停账号调度",
  upstream_monitor_restore_group_rate_sources: "上游监测恢复分组倍率源",
  upstream_monitor_resume_account: "恢复账号调度",
};

export function logActionLabel(action?: string | null) {
  if (!action) return "-";
  return actionLabels[action] ?? action;
}
