// Code generated by ent, DO NOT EDIT.

package adaptivegroupconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the adaptivegroupconfig type in the database.
	Label = "adaptive_group_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldParentGroupID holds the string denoting the parent_group_id field in the database.
	FieldParentGroupID = "parent_group_id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldConfigGeneration holds the string denoting the config_generation field in the database.
	FieldConfigGeneration = "config_generation"
	// EdgeParentGroup holds the string denoting the parent_group edge name in mutations.
	EdgeParentGroup = "parent_group"
	// EdgeMembers holds the string denoting the members edge name in mutations.
	EdgeMembers = "members"
	// Table holds the table name of the adaptivegroupconfig in the database.
	Table = "adaptive_group_configs"
	// ParentGroupTable is the table that holds the parent_group relation/edge.
	ParentGroupTable = "adaptive_group_configs"
	// ParentGroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	ParentGroupInverseTable = "groups"
	// ParentGroupColumn is the table column denoting the parent_group relation/edge.
	ParentGroupColumn = "parent_group_id"
	// MembersTable is the table that holds the members relation/edge.
	MembersTable = "adaptive_group_memberships"
	// MembersInverseTable is the table name for the AdaptiveGroupMembership entity.
	// It exists in this package in order to avoid circular dependency with the "adaptivegroupmembership" package.
	MembersInverseTable = "adaptive_group_memberships"
	// MembersColumn is the table column denoting the members relation/edge.
	MembersColumn = "config_id"
)

// Columns holds all SQL columns for adaptivegroupconfig fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldParentGroupID,
	FieldEnabled,
	FieldConfigGeneration,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ParentGroupIDValidator is a validator for the "parent_group_id" field. It is called by the builders before save.
	ParentGroupIDValidator func(int64) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultConfigGeneration holds the default value on creation for the "config_generation" field.
	DefaultConfigGeneration int64
	// ConfigGenerationValidator is a validator for the "config_generation" field. It is called by the builders before save.
	ConfigGenerationValidator func(int64) error
)

// OrderOption defines the ordering options for the AdaptiveGroupConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByParentGroupID orders the results by the parent_group_id field.
func ByParentGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentGroupID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByConfigGeneration orders the results by the config_generation field.
func ByConfigGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigGeneration, opts...).ToFunc()
}

// ByParentGroupField orders the results by parent_group field.
func ByParentGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByMembersCount orders the results by members count.
func ByMembersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMembersStep(), opts...)
	}
}

// ByMembers orders the results by members terms.
func ByMembers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMembersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newParentGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ParentGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ParentGroupTable, ParentGroupColumn),
	)
}
func newMembersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MembersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, MembersTable, MembersColumn),
	)
}
