// Code generated by ent, DO NOT EDIT.

package adaptivegroupconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// ParentGroupID applies equality check predicate on the "parent_group_id" field. It's identical to ParentGroupIDEQ.
func ParentGroupID(v int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldEQ(FieldParentGroupID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldEQ(FieldEnabled, v))
}

// ConfigGeneration applies equality check predicate on the "config_generation" field. It's identical to ConfigGenerationEQ.
func ConfigGeneration(v int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldEQ(FieldConfigGeneration, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// ParentGroupIDEQ applies the EQ predicate on the "parent_group_id" field.
func ParentGroupIDEQ(v int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldEQ(FieldParentGroupID, v))
}

// ParentGroupIDNEQ applies the NEQ predicate on the "parent_group_id" field.
func ParentGroupIDNEQ(v int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldNEQ(FieldParentGroupID, v))
}

// ParentGroupIDIn applies the In predicate on the "parent_group_id" field.
func ParentGroupIDIn(vs ...int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldIn(FieldParentGroupID, vs...))
}

// ParentGroupIDNotIn applies the NotIn predicate on the "parent_group_id" field.
func ParentGroupIDNotIn(vs ...int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldNotIn(FieldParentGroupID, vs...))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldNEQ(FieldEnabled, v))
}

// ConfigGenerationEQ applies the EQ predicate on the "config_generation" field.
func ConfigGenerationEQ(v int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldEQ(FieldConfigGeneration, v))
}

// ConfigGenerationNEQ applies the NEQ predicate on the "config_generation" field.
func ConfigGenerationNEQ(v int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldNEQ(FieldConfigGeneration, v))
}

// ConfigGenerationIn applies the In predicate on the "config_generation" field.
func ConfigGenerationIn(vs ...int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldIn(FieldConfigGeneration, vs...))
}

// ConfigGenerationNotIn applies the NotIn predicate on the "config_generation" field.
func ConfigGenerationNotIn(vs ...int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldNotIn(FieldConfigGeneration, vs...))
}

// ConfigGenerationGT applies the GT predicate on the "config_generation" field.
func ConfigGenerationGT(v int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldGT(FieldConfigGeneration, v))
}

// ConfigGenerationGTE applies the GTE predicate on the "config_generation" field.
func ConfigGenerationGTE(v int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldGTE(FieldConfigGeneration, v))
}

// ConfigGenerationLT applies the LT predicate on the "config_generation" field.
func ConfigGenerationLT(v int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldLT(FieldConfigGeneration, v))
}

// ConfigGenerationLTE applies the LTE predicate on the "config_generation" field.
func ConfigGenerationLTE(v int64) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.FieldLTE(FieldConfigGeneration, v))
}

// HasParentGroup applies the HasEdge predicate on the "parent_group" edge.
func HasParentGroup() predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ParentGroupTable, ParentGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentGroupWith applies the HasEdge predicate on the "parent_group" edge with a given conditions (other predicates).
func HasParentGroupWith(preds ...predicate.Group) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(func(s *sql.Selector) {
		step := newParentGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMembers applies the HasEdge predicate on the "members" edge.
func HasMembers() predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, MembersTable, MembersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMembersWith applies the HasEdge predicate on the "members" edge with a given conditions (other predicates).
func HasMembersWith(preds ...predicate.AdaptiveGroupMembership) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(func(s *sql.Selector) {
		step := newMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdaptiveGroupConfig) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdaptiveGroupConfig) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdaptiveGroupConfig) predicate.AdaptiveGroupConfig {
	return predicate.AdaptiveGroupConfig(sql.NotPredicates(p))
}
