// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adaptivegroupconfig"
	"github.com/Wei-Shaw/sub2api/ent/adaptivegroupmembership"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AdaptiveGroupConfigUpdate is the builder for updating AdaptiveGroupConfig entities.
type AdaptiveGroupConfigUpdate struct {
	config
	hooks    []Hook
	mutation *AdaptiveGroupConfigMutation
}

// Where appends a list predicates to the AdaptiveGroupConfigUpdate builder.
func (_u *AdaptiveGroupConfigUpdate) Where(ps ...predicate.AdaptiveGroupConfig) *AdaptiveGroupConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdaptiveGroupConfigUpdate) SetUpdatedAt(v time.Time) *AdaptiveGroupConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetParentGroupID sets the "parent_group_id" field.
func (_u *AdaptiveGroupConfigUpdate) SetParentGroupID(v int64) *AdaptiveGroupConfigUpdate {
	_u.mutation.SetParentGroupID(v)
	return _u
}

// SetNillableParentGroupID sets the "parent_group_id" field if the given value is not nil.
func (_u *AdaptiveGroupConfigUpdate) SetNillableParentGroupID(v *int64) *AdaptiveGroupConfigUpdate {
	if v != nil {
		_u.SetParentGroupID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AdaptiveGroupConfigUpdate) SetEnabled(v bool) *AdaptiveGroupConfigUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AdaptiveGroupConfigUpdate) SetNillableEnabled(v *bool) *AdaptiveGroupConfigUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetConfigGeneration sets the "config_generation" field.
func (_u *AdaptiveGroupConfigUpdate) SetConfigGeneration(v int64) *AdaptiveGroupConfigUpdate {
	_u.mutation.ResetConfigGeneration()
	_u.mutation.SetConfigGeneration(v)
	return _u
}

// SetNillableConfigGeneration sets the "config_generation" field if the given value is not nil.
func (_u *AdaptiveGroupConfigUpdate) SetNillableConfigGeneration(v *int64) *AdaptiveGroupConfigUpdate {
	if v != nil {
		_u.SetConfigGeneration(*v)
	}
	return _u
}

// AddConfigGeneration adds value to the "config_generation" field.
func (_u *AdaptiveGroupConfigUpdate) AddConfigGeneration(v int64) *AdaptiveGroupConfigUpdate {
	_u.mutation.AddConfigGeneration(v)
	return _u
}

// SetParentGroup sets the "parent_group" edge to the Group entity.
func (_u *AdaptiveGroupConfigUpdate) SetParentGroup(v *Group) *AdaptiveGroupConfigUpdate {
	return _u.SetParentGroupID(v.ID)
}

// AddMemberIDs adds the "members" edge to the AdaptiveGroupMembership entity by IDs.
func (_u *AdaptiveGroupConfigUpdate) AddMemberIDs(ids ...int64) *AdaptiveGroupConfigUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the AdaptiveGroupMembership entity.
func (_u *AdaptiveGroupConfigUpdate) AddMembers(v ...*AdaptiveGroupMembership) *AdaptiveGroupConfigUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the AdaptiveGroupConfigMutation object of the builder.
func (_u *AdaptiveGroupConfigUpdate) Mutation() *AdaptiveGroupConfigMutation {
	return _u.mutation
}

// ClearParentGroup clears the "parent_group" edge to the Group entity.
func (_u *AdaptiveGroupConfigUpdate) ClearParentGroup() *AdaptiveGroupConfigUpdate {
	_u.mutation.ClearParentGroup()
	return _u
}

// ClearMembers clears all "members" edges to the AdaptiveGroupMembership entity.
func (_u *AdaptiveGroupConfigUpdate) ClearMembers() *AdaptiveGroupConfigUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to AdaptiveGroupMembership entities by IDs.
func (_u *AdaptiveGroupConfigUpdate) RemoveMemberIDs(ids ...int64) *AdaptiveGroupConfigUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to AdaptiveGroupMembership entities.
func (_u *AdaptiveGroupConfigUpdate) RemoveMembers(v ...*AdaptiveGroupMembership) *AdaptiveGroupConfigUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdaptiveGroupConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdaptiveGroupConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdaptiveGroupConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdaptiveGroupConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdaptiveGroupConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adaptivegroupconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdaptiveGroupConfigUpdate) check() error {
	if v, ok := _u.mutation.ParentGroupID(); ok {
		if err := adaptivegroupconfig.ParentGroupIDValidator(v); err != nil {
			return &ValidationError{Name: "parent_group_id", err: fmt.Errorf(`ent: validator failed for field "AdaptiveGroupConfig.parent_group_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfigGeneration(); ok {
		if err := adaptivegroupconfig.ConfigGenerationValidator(v); err != nil {
			return &ValidationError{Name: "config_generation", err: fmt.Errorf(`ent: validator failed for field "AdaptiveGroupConfig.config_generation": %w`, err)}
		}
	}
	if _u.mutation.ParentGroupCleared() && len(_u.mutation.ParentGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdaptiveGroupConfig.parent_group"`)
	}
	return nil
}

func (_u *AdaptiveGroupConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adaptivegroupconfig.Table, adaptivegroupconfig.Columns, sqlgraph.NewFieldSpec(adaptivegroupconfig.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adaptivegroupconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(adaptivegroupconfig.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConfigGeneration(); ok {
		_spec.SetField(adaptivegroupconfig.FieldConfigGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConfigGeneration(); ok {
		_spec.AddField(adaptivegroupconfig.FieldConfigGeneration, field.TypeInt64, value)
	}
	if _u.mutation.ParentGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adaptivegroupconfig.ParentGroupTable,
			Columns: []string{adaptivegroupconfig.ParentGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adaptivegroupconfig.ParentGroupTable,
			Columns: []string{adaptivegroupconfig.ParentGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   adaptivegroupconfig.MembersTable,
			Columns: []string{adaptivegroupconfig.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adaptivegroupmembership.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   adaptivegroupconfig.MembersTable,
			Columns: []string{adaptivegroupconfig.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adaptivegroupmembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   adaptivegroupconfig.MembersTable,
			Columns: []string{adaptivegroupconfig.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adaptivegroupmembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adaptivegroupconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdaptiveGroupConfigUpdateOne is the builder for updating a single AdaptiveGroupConfig entity.
type AdaptiveGroupConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdaptiveGroupConfigMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdaptiveGroupConfigUpdateOne) SetUpdatedAt(v time.Time) *AdaptiveGroupConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetParentGroupID sets the "parent_group_id" field.
func (_u *AdaptiveGroupConfigUpdateOne) SetParentGroupID(v int64) *AdaptiveGroupConfigUpdateOne {
	_u.mutation.SetParentGroupID(v)
	return _u
}

// SetNillableParentGroupID sets the "parent_group_id" field if the given value is not nil.
func (_u *AdaptiveGroupConfigUpdateOne) SetNillableParentGroupID(v *int64) *AdaptiveGroupConfigUpdateOne {
	if v != nil {
		_u.SetParentGroupID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AdaptiveGroupConfigUpdateOne) SetEnabled(v bool) *AdaptiveGroupConfigUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AdaptiveGroupConfigUpdateOne) SetNillableEnabled(v *bool) *AdaptiveGroupConfigUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetConfigGeneration sets the "config_generation" field.
func (_u *AdaptiveGroupConfigUpdateOne) SetConfigGeneration(v int64) *AdaptiveGroupConfigUpdateOne {
	_u.mutation.ResetConfigGeneration()
	_u.mutation.SetConfigGeneration(v)
	return _u
}

// SetNillableConfigGeneration sets the "config_generation" field if the given value is not nil.
func (_u *AdaptiveGroupConfigUpdateOne) SetNillableConfigGeneration(v *int64) *AdaptiveGroupConfigUpdateOne {
	if v != nil {
		_u.SetConfigGeneration(*v)
	}
	return _u
}

// AddConfigGeneration adds value to the "config_generation" field.
func (_u *AdaptiveGroupConfigUpdateOne) AddConfigGeneration(v int64) *AdaptiveGroupConfigUpdateOne {
	_u.mutation.AddConfigGeneration(v)
	return _u
}

// SetParentGroup sets the "parent_group" edge to the Group entity.
func (_u *AdaptiveGroupConfigUpdateOne) SetParentGroup(v *Group) *AdaptiveGroupConfigUpdateOne {
	return _u.SetParentGroupID(v.ID)
}

// AddMemberIDs adds the "members" edge to the AdaptiveGroupMembership entity by IDs.
func (_u *AdaptiveGroupConfigUpdateOne) AddMemberIDs(ids ...int64) *AdaptiveGroupConfigUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the AdaptiveGroupMembership entity.
func (_u *AdaptiveGroupConfigUpdateOne) AddMembers(v ...*AdaptiveGroupMembership) *AdaptiveGroupConfigUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the AdaptiveGroupConfigMutation object of the builder.
func (_u *AdaptiveGroupConfigUpdateOne) Mutation() *AdaptiveGroupConfigMutation {
	return _u.mutation
}

// ClearParentGroup clears the "parent_group" edge to the Group entity.
func (_u *AdaptiveGroupConfigUpdateOne) ClearParentGroup() *AdaptiveGroupConfigUpdateOne {
	_u.mutation.ClearParentGroup()
	return _u
}

// ClearMembers clears all "members" edges to the AdaptiveGroupMembership entity.
func (_u *AdaptiveGroupConfigUpdateOne) ClearMembers() *AdaptiveGroupConfigUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to AdaptiveGroupMembership entities by IDs.
func (_u *AdaptiveGroupConfigUpdateOne) RemoveMemberIDs(ids ...int64) *AdaptiveGroupConfigUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to AdaptiveGroupMembership entities.
func (_u *AdaptiveGroupConfigUpdateOne) RemoveMembers(v ...*AdaptiveGroupMembership) *AdaptiveGroupConfigUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Where appends a list predicates to the AdaptiveGroupConfigUpdate builder.
func (_u *AdaptiveGroupConfigUpdateOne) Where(ps ...predicate.AdaptiveGroupConfig) *AdaptiveGroupConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdaptiveGroupConfigUpdateOne) Select(field string, fields ...string) *AdaptiveGroupConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdaptiveGroupConfig entity.
func (_u *AdaptiveGroupConfigUpdateOne) Save(ctx context.Context) (*AdaptiveGroupConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdaptiveGroupConfigUpdateOne) SaveX(ctx context.Context) *AdaptiveGroupConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdaptiveGroupConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdaptiveGroupConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdaptiveGroupConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adaptivegroupconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdaptiveGroupConfigUpdateOne) check() error {
	if v, ok := _u.mutation.ParentGroupID(); ok {
		if err := adaptivegroupconfig.ParentGroupIDValidator(v); err != nil {
			return &ValidationError{Name: "parent_group_id", err: fmt.Errorf(`ent: validator failed for field "AdaptiveGroupConfig.parent_group_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfigGeneration(); ok {
		if err := adaptivegroupconfig.ConfigGenerationValidator(v); err != nil {
			return &ValidationError{Name: "config_generation", err: fmt.Errorf(`ent: validator failed for field "AdaptiveGroupConfig.config_generation": %w`, err)}
		}
	}
	if _u.mutation.ParentGroupCleared() && len(_u.mutation.ParentGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdaptiveGroupConfig.parent_group"`)
	}
	return nil
}

func (_u *AdaptiveGroupConfigUpdateOne) sqlSave(ctx context.Context) (_node *AdaptiveGroupConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adaptivegroupconfig.Table, adaptivegroupconfig.Columns, sqlgraph.NewFieldSpec(adaptivegroupconfig.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdaptiveGroupConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adaptivegroupconfig.FieldID)
		for _, f := range fields {
			if !adaptivegroupconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adaptivegroupconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adaptivegroupconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(adaptivegroupconfig.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConfigGeneration(); ok {
		_spec.SetField(adaptivegroupconfig.FieldConfigGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConfigGeneration(); ok {
		_spec.AddField(adaptivegroupconfig.FieldConfigGeneration, field.TypeInt64, value)
	}
	if _u.mutation.ParentGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adaptivegroupconfig.ParentGroupTable,
			Columns: []string{adaptivegroupconfig.ParentGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adaptivegroupconfig.ParentGroupTable,
			Columns: []string{adaptivegroupconfig.ParentGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   adaptivegroupconfig.MembersTable,
			Columns: []string{adaptivegroupconfig.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adaptivegroupmembership.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   adaptivegroupconfig.MembersTable,
			Columns: []string{adaptivegroupconfig.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adaptivegroupmembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   adaptivegroupconfig.MembersTable,
			Columns: []string{adaptivegroupconfig.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adaptivegroupmembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AdaptiveGroupConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adaptivegroupconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
