// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adaptivegroupconfig"
	"github.com/Wei-Shaw/sub2api/ent/adaptivegroupmembership"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AdaptiveGroupMembershipUpdate is the builder for updating AdaptiveGroupMembership entities.
type AdaptiveGroupMembershipUpdate struct {
	config
	hooks    []Hook
	mutation *AdaptiveGroupMembershipMutation
}

// Where appends a list predicates to the AdaptiveGroupMembershipUpdate builder.
func (_u *AdaptiveGroupMembershipUpdate) Where(ps ...predicate.AdaptiveGroupMembership) *AdaptiveGroupMembershipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdaptiveGroupMembershipUpdate) SetUpdatedAt(v time.Time) *AdaptiveGroupMembershipUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConfigID sets the "config_id" field.
func (_u *AdaptiveGroupMembershipUpdate) SetConfigID(v int64) *AdaptiveGroupMembershipUpdate {
	_u.mutation.SetConfigID(v)
	return _u
}

// SetNillableConfigID sets the "config_id" field if the given value is not nil.
func (_u *AdaptiveGroupMembershipUpdate) SetNillableConfigID(v *int64) *AdaptiveGroupMembershipUpdate {
	if v != nil {
		_u.SetConfigID(*v)
	}
	return _u
}

// SetLeafGroupID sets the "leaf_group_id" field.
func (_u *AdaptiveGroupMembershipUpdate) SetLeafGroupID(v int64) *AdaptiveGroupMembershipUpdate {
	_u.mutation.SetLeafGroupID(v)
	return _u
}

// SetNillableLeafGroupID sets the "leaf_group_id" field if the given value is not nil.
func (_u *AdaptiveGroupMembershipUpdate) SetNillableLeafGroupID(v *int64) *AdaptiveGroupMembershipUpdate {
	if v != nil {
		_u.SetLeafGroupID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AdaptiveGroupMembershipUpdate) SetEnabled(v bool) *AdaptiveGroupMembershipUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AdaptiveGroupMembershipUpdate) SetNillableEnabled(v *bool) *AdaptiveGroupMembershipUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AdaptiveGroupMembershipUpdate) SetSortOrder(v int) *AdaptiveGroupMembershipUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AdaptiveGroupMembershipUpdate) SetNillableSortOrder(v *int) *AdaptiveGroupMembershipUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AdaptiveGroupMembershipUpdate) AddSortOrder(v int) *AdaptiveGroupMembershipUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetConfig sets the "config" edge to the AdaptiveGroupConfig entity.
func (_u *AdaptiveGroupMembershipUpdate) SetConfig(v *AdaptiveGroupConfig) *AdaptiveGroupMembershipUpdate {
	return _u.SetConfigID(v.ID)
}

// SetLeafGroup sets the "leaf_group" edge to the Group entity.
func (_u *AdaptiveGroupMembershipUpdate) SetLeafGroup(v *Group) *AdaptiveGroupMembershipUpdate {
	return _u.SetLeafGroupID(v.ID)
}

// Mutation returns the AdaptiveGroupMembershipMutation object of the builder.
func (_u *AdaptiveGroupMembershipUpdate) Mutation() *AdaptiveGroupMembershipMutation {
	return _u.mutation
}

// ClearConfig clears the "config" edge to the AdaptiveGroupConfig entity.
func (_u *AdaptiveGroupMembershipUpdate) ClearConfig() *AdaptiveGroupMembershipUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// ClearLeafGroup clears the "leaf_group" edge to the Group entity.
func (_u *AdaptiveGroupMembershipUpdate) ClearLeafGroup() *AdaptiveGroupMembershipUpdate {
	_u.mutation.ClearLeafGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdaptiveGroupMembershipUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdaptiveGroupMembershipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdaptiveGroupMembershipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdaptiveGroupMembershipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdaptiveGroupMembershipUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adaptivegroupmembership.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdaptiveGroupMembershipUpdate) check() error {
	if v, ok := _u.mutation.ConfigID(); ok {
		if err := adaptivegroupmembership.ConfigIDValidator(v); err != nil {
			return &ValidationError{Name: "config_id", err: fmt.Errorf(`ent: validator failed for field "AdaptiveGroupMembership.config_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeafGroupID(); ok {
		if err := adaptivegroupmembership.LeafGroupIDValidator(v); err != nil {
			return &ValidationError{Name: "leaf_group_id", err: fmt.Errorf(`ent: validator failed for field "AdaptiveGroupMembership.leaf_group_id": %w`, err)}
		}
	}
	if _u.mutation.ConfigCleared() && len(_u.mutation.ConfigIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdaptiveGroupMembership.config"`)
	}
	if _u.mutation.LeafGroupCleared() && len(_u.mutation.LeafGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdaptiveGroupMembership.leaf_group"`)
	}
	return nil
}

func (_u *AdaptiveGroupMembershipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adaptivegroupmembership.Table, adaptivegroupmembership.Columns, sqlgraph.NewFieldSpec(adaptivegroupmembership.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adaptivegroupmembership.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(adaptivegroupmembership.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(adaptivegroupmembership.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(adaptivegroupmembership.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.ConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adaptivegroupmembership.ConfigTable,
			Columns: []string{adaptivegroupmembership.ConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adaptivegroupconfig.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adaptivegroupmembership.ConfigTable,
			Columns: []string{adaptivegroupmembership.ConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adaptivegroupconfig.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LeafGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adaptivegroupmembership.LeafGroupTable,
			Columns: []string{adaptivegroupmembership.LeafGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeafGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adaptivegroupmembership.LeafGroupTable,
			Columns: []string{adaptivegroupmembership.LeafGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adaptivegroupmembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdaptiveGroupMembershipUpdateOne is the builder for updating a single AdaptiveGroupMembership entity.
type AdaptiveGroupMembershipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdaptiveGroupMembershipMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdaptiveGroupMembershipUpdateOne) SetUpdatedAt(v time.Time) *AdaptiveGroupMembershipUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConfigID sets the "config_id" field.
func (_u *AdaptiveGroupMembershipUpdateOne) SetConfigID(v int64) *AdaptiveGroupMembershipUpdateOne {
	_u.mutation.SetConfigID(v)
	return _u
}

// SetNillableConfigID sets the "config_id" field if the given value is not nil.
func (_u *AdaptiveGroupMembershipUpdateOne) SetNillableConfigID(v *int64) *AdaptiveGroupMembershipUpdateOne {
	if v != nil {
		_u.SetConfigID(*v)
	}
	return _u
}

// SetLeafGroupID sets the "leaf_group_id" field.
func (_u *AdaptiveGroupMembershipUpdateOne) SetLeafGroupID(v int64) *AdaptiveGroupMembershipUpdateOne {
	_u.mutation.SetLeafGroupID(v)
	return _u
}

// SetNillableLeafGroupID sets the "leaf_group_id" field if the given value is not nil.
func (_u *AdaptiveGroupMembershipUpdateOne) SetNillableLeafGroupID(v *int64) *AdaptiveGroupMembershipUpdateOne {
	if v != nil {
		_u.SetLeafGroupID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AdaptiveGroupMembershipUpdateOne) SetEnabled(v bool) *AdaptiveGroupMembershipUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AdaptiveGroupMembershipUpdateOne) SetNillableEnabled(v *bool) *AdaptiveGroupMembershipUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AdaptiveGroupMembershipUpdateOne) SetSortOrder(v int) *AdaptiveGroupMembershipUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AdaptiveGroupMembershipUpdateOne) SetNillableSortOrder(v *int) *AdaptiveGroupMembershipUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AdaptiveGroupMembershipUpdateOne) AddSortOrder(v int) *AdaptiveGroupMembershipUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetConfig sets the "config" edge to the AdaptiveGroupConfig entity.
func (_u *AdaptiveGroupMembershipUpdateOne) SetConfig(v *AdaptiveGroupConfig) *AdaptiveGroupMembershipUpdateOne {
	return _u.SetConfigID(v.ID)
}

// SetLeafGroup sets the "leaf_group" edge to the Group entity.
func (_u *AdaptiveGroupMembershipUpdateOne) SetLeafGroup(v *Group) *AdaptiveGroupMembershipUpdateOne {
	return _u.SetLeafGroupID(v.ID)
}

// Mutation returns the AdaptiveGroupMembershipMutation object of the builder.
func (_u *AdaptiveGroupMembershipUpdateOne) Mutation() *AdaptiveGroupMembershipMutation {
	return _u.mutation
}

// ClearConfig clears the "config" edge to the AdaptiveGroupConfig entity.
func (_u *AdaptiveGroupMembershipUpdateOne) ClearConfig() *AdaptiveGroupMembershipUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// ClearLeafGroup clears the "leaf_group" edge to the Group entity.
func (_u *AdaptiveGroupMembershipUpdateOne) ClearLeafGroup() *AdaptiveGroupMembershipUpdateOne {
	_u.mutation.ClearLeafGroup()
	return _u
}

// Where appends a list predicates to the AdaptiveGroupMembershipUpdate builder.
func (_u *AdaptiveGroupMembershipUpdateOne) Where(ps ...predicate.AdaptiveGroupMembership) *AdaptiveGroupMembershipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdaptiveGroupMembershipUpdateOne) Select(field string, fields ...string) *AdaptiveGroupMembershipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdaptiveGroupMembership entity.
func (_u *AdaptiveGroupMembershipUpdateOne) Save(ctx context.Context) (*AdaptiveGroupMembership, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdaptiveGroupMembershipUpdateOne) SaveX(ctx context.Context) *AdaptiveGroupMembership {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdaptiveGroupMembershipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdaptiveGroupMembershipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdaptiveGroupMembershipUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adaptivegroupmembership.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdaptiveGroupMembershipUpdateOne) check() error {
	if v, ok := _u.mutation.ConfigID(); ok {
		if err := adaptivegroupmembership.ConfigIDValidator(v); err != nil {
			return &ValidationError{Name: "config_id", err: fmt.Errorf(`ent: validator failed for field "AdaptiveGroupMembership.config_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeafGroupID(); ok {
		if err := adaptivegroupmembership.LeafGroupIDValidator(v); err != nil {
			return &ValidationError{Name: "leaf_group_id", err: fmt.Errorf(`ent: validator failed for field "AdaptiveGroupMembership.leaf_group_id": %w`, err)}
		}
	}
	if _u.mutation.ConfigCleared() && len(_u.mutation.ConfigIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdaptiveGroupMembership.config"`)
	}
	if _u.mutation.LeafGroupCleared() && len(_u.mutation.LeafGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdaptiveGroupMembership.leaf_group"`)
	}
	return nil
}

func (_u *AdaptiveGroupMembershipUpdateOne) sqlSave(ctx context.Context) (_node *AdaptiveGroupMembership, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adaptivegroupmembership.Table, adaptivegroupmembership.Columns, sqlgraph.NewFieldSpec(adaptivegroupmembership.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdaptiveGroupMembership.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adaptivegroupmembership.FieldID)
		for _, f := range fields {
			if !adaptivegroupmembership.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adaptivegroupmembership.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adaptivegroupmembership.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(adaptivegroupmembership.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(adaptivegroupmembership.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(adaptivegroupmembership.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.ConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adaptivegroupmembership.ConfigTable,
			Columns: []string{adaptivegroupmembership.ConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adaptivegroupconfig.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adaptivegroupmembership.ConfigTable,
			Columns: []string{adaptivegroupmembership.ConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adaptivegroupconfig.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LeafGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adaptivegroupmembership.LeafGroupTable,
			Columns: []string{adaptivegroupmembership.LeafGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeafGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adaptivegroupmembership.LeafGroupTable,
			Columns: []string{adaptivegroupmembership.LeafGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AdaptiveGroupMembership{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adaptivegroupmembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
