// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adaptivegroupconfig"
	"github.com/Wei-Shaw/sub2api/ent/adaptivegroupmembership"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// AdaptiveGroupMembershipCreate is the builder for creating a AdaptiveGroupMembership entity.
type AdaptiveGroupMembershipCreate struct {
	config
	mutation *AdaptiveGroupMembershipMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdaptiveGroupMembershipCreate) SetCreatedAt(v time.Time) *AdaptiveGroupMembershipCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdaptiveGroupMembershipCreate) SetNillableCreatedAt(v *time.Time) *AdaptiveGroupMembershipCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AdaptiveGroupMembershipCreate) SetUpdatedAt(v time.Time) *AdaptiveGroupMembershipCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AdaptiveGroupMembershipCreate) SetNillableUpdatedAt(v *time.Time) *AdaptiveGroupMembershipCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetConfigID sets the "config_id" field.
func (_c *AdaptiveGroupMembershipCreate) SetConfigID(v int64) *AdaptiveGroupMembershipCreate {
	_c.mutation.SetConfigID(v)
	return _c
}

// SetLeafGroupID sets the "leaf_group_id" field.
func (_c *AdaptiveGroupMembershipCreate) SetLeafGroupID(v int64) *AdaptiveGroupMembershipCreate {
	_c.mutation.SetLeafGroupID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *AdaptiveGroupMembershipCreate) SetEnabled(v bool) *AdaptiveGroupMembershipCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *AdaptiveGroupMembershipCreate) SetNillableEnabled(v *bool) *AdaptiveGroupMembershipCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *AdaptiveGroupMembershipCreate) SetSortOrder(v int) *AdaptiveGroupMembershipCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *AdaptiveGroupMembershipCreate) SetNillableSortOrder(v *int) *AdaptiveGroupMembershipCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetConfig sets the "config" edge to the AdaptiveGroupConfig entity.
func (_c *AdaptiveGroupMembershipCreate) SetConfig(v *AdaptiveGroupConfig) *AdaptiveGroupMembershipCreate {
	return _c.SetConfigID(v.ID)
}

// SetLeafGroup sets the "leaf_group" edge to the Group entity.
func (_c *AdaptiveGroupMembershipCreate) SetLeafGroup(v *Group) *AdaptiveGroupMembershipCreate {
	return _c.SetLeafGroupID(v.ID)
}

// Mutation returns the AdaptiveGroupMembershipMutation object of the builder.
func (_c *AdaptiveGroupMembershipCreate) Mutation() *AdaptiveGroupMembershipMutation {
	return _c.mutation
}

// Save creates the AdaptiveGroupMembership in the database.
func (_c *AdaptiveGroupMembershipCreate) Save(ctx context.Context) (*AdaptiveGroupMembership, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdaptiveGroupMembershipCreate) SaveX(ctx context.Context) *AdaptiveGroupMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdaptiveGroupMembershipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdaptiveGroupMembershipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdaptiveGroupMembershipCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := adaptivegroupmembership.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := adaptivegroupmembership.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := adaptivegroupmembership.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := adaptivegroupmembership.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdaptiveGroupMembershipCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdaptiveGroupMembership.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AdaptiveGroupMembership.updated_at"`)}
	}
	if _, ok := _c.mutation.ConfigID(); !ok {
		return &ValidationError{Name: "config_id", err: errors.New(`ent: missing required field "AdaptiveGroupMembership.config_id"`)}
	}
	if v, ok := _c.mutation.ConfigID(); ok {
		if err := adaptivegroupmembership.ConfigIDValidator(v); err != nil {
			return &ValidationError{Name: "config_id", err: fmt.Errorf(`ent: validator failed for field "AdaptiveGroupMembership.config_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LeafGroupID(); !ok {
		return &ValidationError{Name: "leaf_group_id", err: errors.New(`ent: missing required field "AdaptiveGroupMembership.leaf_group_id"`)}
	}
	if v, ok := _c.mutation.LeafGroupID(); ok {
		if err := adaptivegroupmembership.LeafGroupIDValidator(v); err != nil {
			return &ValidationError{Name: "leaf_group_id", err: fmt.Errorf(`ent: validator failed for field "AdaptiveGroupMembership.leaf_group_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "AdaptiveGroupMembership.enabled"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "AdaptiveGroupMembership.sort_order"`)}
	}
	if len(_c.mutation.ConfigIDs()) == 0 {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required edge "AdaptiveGroupMembership.config"`)}
	}
	if len(_c.mutation.LeafGroupIDs()) == 0 {
		return &ValidationError{Name: "leaf_group", err: errors.New(`ent: missing required edge "AdaptiveGroupMembership.leaf_group"`)}
	}
	return nil
}

func (_c *AdaptiveGroupMembershipCreate) sqlSave(ctx context.Context) (*AdaptiveGroupMembership, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdaptiveGroupMembershipCreate) createSpec() (*AdaptiveGroupMembership, *sqlgraph.CreateSpec) {
	var (
		_node = &AdaptiveGroupMembership{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adaptivegroupmembership.Table, sqlgraph.NewFieldSpec(adaptivegroupmembership.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adaptivegroupmembership.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(adaptivegroupmembership.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(adaptivegroupmembership.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(adaptivegroupmembership.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.ConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adaptivegroupmembership.ConfigTable,
			Columns: []string{adaptivegroupmembership.ConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adaptivegroupconfig.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConfigID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LeafGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adaptivegroupmembership.LeafGroupTable,
			Columns: []string{adaptivegroupmembership.LeafGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LeafGroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdaptiveGroupMembership.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdaptiveGroupMembershipUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AdaptiveGroupMembershipCreate) OnConflict(opts ...sql.ConflictOption) *AdaptiveGroupMembershipUpsertOne {
	_c.conflict = opts
	return &AdaptiveGroupMembershipUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdaptiveGroupMembership.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdaptiveGroupMembershipCreate) OnConflictColumns(columns ...string) *AdaptiveGroupMembershipUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdaptiveGroupMembershipUpsertOne{
		create: _c,
	}
}

type (
	// AdaptiveGroupMembershipUpsertOne is the builder for "upsert"-ing
	//  one AdaptiveGroupMembership node.
	AdaptiveGroupMembershipUpsertOne struct {
		create *AdaptiveGroupMembershipCreate
	}

	// AdaptiveGroupMembershipUpsert is the "OnConflict" setter.
	AdaptiveGroupMembershipUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AdaptiveGroupMembershipUpsert) SetUpdatedAt(v time.Time) *AdaptiveGroupMembershipUpsert {
	u.Set(adaptivegroupmembership.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdaptiveGroupMembershipUpsert) UpdateUpdatedAt() *AdaptiveGroupMembershipUpsert {
	u.SetExcluded(adaptivegroupmembership.FieldUpdatedAt)
	return u
}

// SetConfigID sets the "config_id" field.
func (u *AdaptiveGroupMembershipUpsert) SetConfigID(v int64) *AdaptiveGroupMembershipUpsert {
	u.Set(adaptivegroupmembership.FieldConfigID, v)
	return u
}

// UpdateConfigID sets the "config_id" field to the value that was provided on create.
func (u *AdaptiveGroupMembershipUpsert) UpdateConfigID() *AdaptiveGroupMembershipUpsert {
	u.SetExcluded(adaptivegroupmembership.FieldConfigID)
	return u
}

// SetLeafGroupID sets the "leaf_group_id" field.
func (u *AdaptiveGroupMembershipUpsert) SetLeafGroupID(v int64) *AdaptiveGroupMembershipUpsert {
	u.Set(adaptivegroupmembership.FieldLeafGroupID, v)
	return u
}

// UpdateLeafGroupID sets the "leaf_group_id" field to the value that was provided on create.
func (u *AdaptiveGroupMembershipUpsert) UpdateLeafGroupID() *AdaptiveGroupMembershipUpsert {
	u.SetExcluded(adaptivegroupmembership.FieldLeafGroupID)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *AdaptiveGroupMembershipUpsert) SetEnabled(v bool) *AdaptiveGroupMembershipUpsert {
	u.Set(adaptivegroupmembership.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AdaptiveGroupMembershipUpsert) UpdateEnabled() *AdaptiveGroupMembershipUpsert {
	u.SetExcluded(adaptivegroupmembership.FieldEnabled)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *AdaptiveGroupMembershipUpsert) SetSortOrder(v int) *AdaptiveGroupMembershipUpsert {
	u.Set(adaptivegroupmembership.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AdaptiveGroupMembershipUpsert) UpdateSortOrder() *AdaptiveGroupMembershipUpsert {
	u.SetExcluded(adaptivegroupmembership.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AdaptiveGroupMembershipUpsert) AddSortOrder(v int) *AdaptiveGroupMembershipUpsert {
	u.Add(adaptivegroupmembership.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AdaptiveGroupMembership.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdaptiveGroupMembershipUpsertOne) UpdateNewValues() *AdaptiveGroupMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(adaptivegroupmembership.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdaptiveGroupMembership.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AdaptiveGroupMembershipUpsertOne) Ignore() *AdaptiveGroupMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdaptiveGroupMembershipUpsertOne) DoNothing() *AdaptiveGroupMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdaptiveGroupMembershipCreate.OnConflict
// documentation for more info.
func (u *AdaptiveGroupMembershipUpsertOne) Update(set func(*AdaptiveGroupMembershipUpsert)) *AdaptiveGroupMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdaptiveGroupMembershipUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AdaptiveGroupMembershipUpsertOne) SetUpdatedAt(v time.Time) *AdaptiveGroupMembershipUpsertOne {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdaptiveGroupMembershipUpsertOne) UpdateUpdatedAt() *AdaptiveGroupMembershipUpsertOne {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetConfigID sets the "config_id" field.
func (u *AdaptiveGroupMembershipUpsertOne) SetConfigID(v int64) *AdaptiveGroupMembershipUpsertOne {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.SetConfigID(v)
	})
}

// UpdateConfigID sets the "config_id" field to the value that was provided on create.
func (u *AdaptiveGroupMembershipUpsertOne) UpdateConfigID() *AdaptiveGroupMembershipUpsertOne {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.UpdateConfigID()
	})
}

// SetLeafGroupID sets the "leaf_group_id" field.
func (u *AdaptiveGroupMembershipUpsertOne) SetLeafGroupID(v int64) *AdaptiveGroupMembershipUpsertOne {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.SetLeafGroupID(v)
	})
}

// UpdateLeafGroupID sets the "leaf_group_id" field to the value that was provided on create.
func (u *AdaptiveGroupMembershipUpsertOne) UpdateLeafGroupID() *AdaptiveGroupMembershipUpsertOne {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.UpdateLeafGroupID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *AdaptiveGroupMembershipUpsertOne) SetEnabled(v bool) *AdaptiveGroupMembershipUpsertOne {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AdaptiveGroupMembershipUpsertOne) UpdateEnabled() *AdaptiveGroupMembershipUpsertOne {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *AdaptiveGroupMembershipUpsertOne) SetSortOrder(v int) *AdaptiveGroupMembershipUpsertOne {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AdaptiveGroupMembershipUpsertOne) AddSortOrder(v int) *AdaptiveGroupMembershipUpsertOne {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AdaptiveGroupMembershipUpsertOne) UpdateSortOrder() *AdaptiveGroupMembershipUpsertOne {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *AdaptiveGroupMembershipUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdaptiveGroupMembershipCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdaptiveGroupMembershipUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AdaptiveGroupMembershipUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AdaptiveGroupMembershipUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AdaptiveGroupMembershipCreateBulk is the builder for creating many AdaptiveGroupMembership entities in bulk.
type AdaptiveGroupMembershipCreateBulk struct {
	config
	err      error
	builders []*AdaptiveGroupMembershipCreate
	conflict []sql.ConflictOption
}

// Save creates the AdaptiveGroupMembership entities in the database.
func (_c *AdaptiveGroupMembershipCreateBulk) Save(ctx context.Context) ([]*AdaptiveGroupMembership, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdaptiveGroupMembership, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdaptiveGroupMembershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdaptiveGroupMembershipCreateBulk) SaveX(ctx context.Context) []*AdaptiveGroupMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdaptiveGroupMembershipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdaptiveGroupMembershipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdaptiveGroupMembership.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdaptiveGroupMembershipUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AdaptiveGroupMembershipCreateBulk) OnConflict(opts ...sql.ConflictOption) *AdaptiveGroupMembershipUpsertBulk {
	_c.conflict = opts
	return &AdaptiveGroupMembershipUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdaptiveGroupMembership.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdaptiveGroupMembershipCreateBulk) OnConflictColumns(columns ...string) *AdaptiveGroupMembershipUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdaptiveGroupMembershipUpsertBulk{
		create: _c,
	}
}

// AdaptiveGroupMembershipUpsertBulk is the builder for "upsert"-ing
// a bulk of AdaptiveGroupMembership nodes.
type AdaptiveGroupMembershipUpsertBulk struct {
	create *AdaptiveGroupMembershipCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AdaptiveGroupMembership.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdaptiveGroupMembershipUpsertBulk) UpdateNewValues() *AdaptiveGroupMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(adaptivegroupmembership.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdaptiveGroupMembership.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AdaptiveGroupMembershipUpsertBulk) Ignore() *AdaptiveGroupMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdaptiveGroupMembershipUpsertBulk) DoNothing() *AdaptiveGroupMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdaptiveGroupMembershipCreateBulk.OnConflict
// documentation for more info.
func (u *AdaptiveGroupMembershipUpsertBulk) Update(set func(*AdaptiveGroupMembershipUpsert)) *AdaptiveGroupMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdaptiveGroupMembershipUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AdaptiveGroupMembershipUpsertBulk) SetUpdatedAt(v time.Time) *AdaptiveGroupMembershipUpsertBulk {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdaptiveGroupMembershipUpsertBulk) UpdateUpdatedAt() *AdaptiveGroupMembershipUpsertBulk {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetConfigID sets the "config_id" field.
func (u *AdaptiveGroupMembershipUpsertBulk) SetConfigID(v int64) *AdaptiveGroupMembershipUpsertBulk {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.SetConfigID(v)
	})
}

// UpdateConfigID sets the "config_id" field to the value that was provided on create.
func (u *AdaptiveGroupMembershipUpsertBulk) UpdateConfigID() *AdaptiveGroupMembershipUpsertBulk {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.UpdateConfigID()
	})
}

// SetLeafGroupID sets the "leaf_group_id" field.
func (u *AdaptiveGroupMembershipUpsertBulk) SetLeafGroupID(v int64) *AdaptiveGroupMembershipUpsertBulk {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.SetLeafGroupID(v)
	})
}

// UpdateLeafGroupID sets the "leaf_group_id" field to the value that was provided on create.
func (u *AdaptiveGroupMembershipUpsertBulk) UpdateLeafGroupID() *AdaptiveGroupMembershipUpsertBulk {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.UpdateLeafGroupID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *AdaptiveGroupMembershipUpsertBulk) SetEnabled(v bool) *AdaptiveGroupMembershipUpsertBulk {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AdaptiveGroupMembershipUpsertBulk) UpdateEnabled() *AdaptiveGroupMembershipUpsertBulk {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *AdaptiveGroupMembershipUpsertBulk) SetSortOrder(v int) *AdaptiveGroupMembershipUpsertBulk {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AdaptiveGroupMembershipUpsertBulk) AddSortOrder(v int) *AdaptiveGroupMembershipUpsertBulk {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AdaptiveGroupMembershipUpsertBulk) UpdateSortOrder() *AdaptiveGroupMembershipUpsertBulk {
	return u.Update(func(s *AdaptiveGroupMembershipUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *AdaptiveGroupMembershipUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AdaptiveGroupMembershipCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdaptiveGroupMembershipCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdaptiveGroupMembershipUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
