// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/adaptivegroupconfig"
	"github.com/Wei-Shaw/sub2api/ent/adaptivegroupmembership"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// AdaptiveGroupMembership is the model entity for the AdaptiveGroupMembership schema.
type AdaptiveGroupMembership struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ConfigID holds the value of the "config_id" field.
	ConfigID int64 `json:"config_id,omitempty"`
	// LeafGroupID holds the value of the "leaf_group_id" field.
	LeafGroupID int64 `json:"leaf_group_id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdaptiveGroupMembershipQuery when eager-loading is set.
	Edges        AdaptiveGroupMembershipEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AdaptiveGroupMembershipEdges holds the relations/edges for other nodes in the graph.
type AdaptiveGroupMembershipEdges struct {
	// Config holds the value of the config edge.
	Config *AdaptiveGroupConfig `json:"config,omitempty"`
	// LeafGroup holds the value of the leaf_group edge.
	LeafGroup *Group `json:"leaf_group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ConfigOrErr returns the Config value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdaptiveGroupMembershipEdges) ConfigOrErr() (*AdaptiveGroupConfig, error) {
	if e.Config != nil {
		return e.Config, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: adaptivegroupconfig.Label}
	}
	return nil, &NotLoadedError{edge: "config"}
}

// LeafGroupOrErr returns the LeafGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdaptiveGroupMembershipEdges) LeafGroupOrErr() (*Group, error) {
	if e.LeafGroup != nil {
		return e.LeafGroup, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "leaf_group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdaptiveGroupMembership) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adaptivegroupmembership.FieldEnabled:
			values[i] = new(sql.NullBool)
		case adaptivegroupmembership.FieldID, adaptivegroupmembership.FieldConfigID, adaptivegroupmembership.FieldLeafGroupID, adaptivegroupmembership.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case adaptivegroupmembership.FieldCreatedAt, adaptivegroupmembership.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdaptiveGroupMembership fields.
func (_m *AdaptiveGroupMembership) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adaptivegroupmembership.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case adaptivegroupmembership.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case adaptivegroupmembership.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case adaptivegroupmembership.FieldConfigID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field config_id", values[i])
			} else if value.Valid {
				_m.ConfigID = value.Int64
			}
		case adaptivegroupmembership.FieldLeafGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field leaf_group_id", values[i])
			} else if value.Valid {
				_m.LeafGroupID = value.Int64
			}
		case adaptivegroupmembership.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case adaptivegroupmembership.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdaptiveGroupMembership.
// This includes values selected through modifiers, order, etc.
func (_m *AdaptiveGroupMembership) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryConfig queries the "config" edge of the AdaptiveGroupMembership entity.
func (_m *AdaptiveGroupMembership) QueryConfig() *AdaptiveGroupConfigQuery {
	return NewAdaptiveGroupMembershipClient(_m.config).QueryConfig(_m)
}

// QueryLeafGroup queries the "leaf_group" edge of the AdaptiveGroupMembership entity.
func (_m *AdaptiveGroupMembership) QueryLeafGroup() *GroupQuery {
	return NewAdaptiveGroupMembershipClient(_m.config).QueryLeafGroup(_m)
}

// Update returns a builder for updating this AdaptiveGroupMembership.
// Note that you need to call AdaptiveGroupMembership.Unwrap() before calling this method if this AdaptiveGroupMembership
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AdaptiveGroupMembership) Update() *AdaptiveGroupMembershipUpdateOne {
	return NewAdaptiveGroupMembershipClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AdaptiveGroupMembership entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AdaptiveGroupMembership) Unwrap() *AdaptiveGroupMembership {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdaptiveGroupMembership is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AdaptiveGroupMembership) String() string {
	var builder strings.Builder
	builder.WriteString("AdaptiveGroupMembership(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("config_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfigID))
	builder.WriteString(", ")
	builder.WriteString("leaf_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LeafGroupID))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// AdaptiveGroupMemberships is a parsable slice of AdaptiveGroupMembership.
type AdaptiveGroupMemberships []*AdaptiveGroupMembership
