// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adaptivegroupmembership"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AdaptiveGroupMembershipDelete is the builder for deleting a AdaptiveGroupMembership entity.
type AdaptiveGroupMembershipDelete struct {
	config
	hooks    []Hook
	mutation *AdaptiveGroupMembershipMutation
}

// Where appends a list predicates to the AdaptiveGroupMembershipDelete builder.
func (_d *AdaptiveGroupMembershipDelete) Where(ps ...predicate.AdaptiveGroupMembership) *AdaptiveGroupMembershipDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AdaptiveGroupMembershipDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdaptiveGroupMembershipDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AdaptiveGroupMembershipDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(adaptivegroupmembership.Table, sqlgraph.NewFieldSpec(adaptivegroupmembership.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AdaptiveGroupMembershipDeleteOne is the builder for deleting a single AdaptiveGroupMembership entity.
type AdaptiveGroupMembershipDeleteOne struct {
	_d *AdaptiveGroupMembershipDelete
}

// Where appends a list predicates to the AdaptiveGroupMembershipDelete builder.
func (_d *AdaptiveGroupMembershipDeleteOne) Where(ps ...predicate.AdaptiveGroupMembership) *AdaptiveGroupMembershipDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AdaptiveGroupMembershipDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{adaptivegroupmembership.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdaptiveGroupMembershipDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
