// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/adaptivegroupconfig"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// AdaptiveGroupConfig is the model entity for the AdaptiveGroupConfig schema.
type AdaptiveGroupConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ParentGroupID holds the value of the "parent_group_id" field.
	ParentGroupID int64 `json:"parent_group_id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Monotonic topology generation frozen into Adaptive route plans
	ConfigGeneration int64 `json:"config_generation,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdaptiveGroupConfigQuery when eager-loading is set.
	Edges        AdaptiveGroupConfigEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AdaptiveGroupConfigEdges holds the relations/edges for other nodes in the graph.
type AdaptiveGroupConfigEdges struct {
	// ParentGroup holds the value of the parent_group edge.
	ParentGroup *Group `json:"parent_group,omitempty"`
	// Members holds the value of the members edge.
	Members []*AdaptiveGroupMembership `json:"members,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ParentGroupOrErr returns the ParentGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdaptiveGroupConfigEdges) ParentGroupOrErr() (*Group, error) {
	if e.ParentGroup != nil {
		return e.ParentGroup, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "parent_group"}
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e AdaptiveGroupConfigEdges) MembersOrErr() ([]*AdaptiveGroupMembership, error) {
	if e.loadedTypes[1] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdaptiveGroupConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adaptivegroupconfig.FieldEnabled:
			values[i] = new(sql.NullBool)
		case adaptivegroupconfig.FieldID, adaptivegroupconfig.FieldParentGroupID, adaptivegroupconfig.FieldConfigGeneration:
			values[i] = new(sql.NullInt64)
		case adaptivegroupconfig.FieldCreatedAt, adaptivegroupconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdaptiveGroupConfig fields.
func (_m *AdaptiveGroupConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adaptivegroupconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case adaptivegroupconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case adaptivegroupconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case adaptivegroupconfig.FieldParentGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_group_id", values[i])
			} else if value.Valid {
				_m.ParentGroupID = value.Int64
			}
		case adaptivegroupconfig.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case adaptivegroupconfig.FieldConfigGeneration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field config_generation", values[i])
			} else if value.Valid {
				_m.ConfigGeneration = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdaptiveGroupConfig.
// This includes values selected through modifiers, order, etc.
func (_m *AdaptiveGroupConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParentGroup queries the "parent_group" edge of the AdaptiveGroupConfig entity.
func (_m *AdaptiveGroupConfig) QueryParentGroup() *GroupQuery {
	return NewAdaptiveGroupConfigClient(_m.config).QueryParentGroup(_m)
}

// QueryMembers queries the "members" edge of the AdaptiveGroupConfig entity.
func (_m *AdaptiveGroupConfig) QueryMembers() *AdaptiveGroupMembershipQuery {
	return NewAdaptiveGroupConfigClient(_m.config).QueryMembers(_m)
}

// Update returns a builder for updating this AdaptiveGroupConfig.
// Note that you need to call AdaptiveGroupConfig.Unwrap() before calling this method if this AdaptiveGroupConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AdaptiveGroupConfig) Update() *AdaptiveGroupConfigUpdateOne {
	return NewAdaptiveGroupConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AdaptiveGroupConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AdaptiveGroupConfig) Unwrap() *AdaptiveGroupConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdaptiveGroupConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AdaptiveGroupConfig) String() string {
	var builder strings.Builder
	builder.WriteString("AdaptiveGroupConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("parent_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentGroupID))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("config_generation=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfigGeneration))
	builder.WriteByte(')')
	return builder.String()
}

// AdaptiveGroupConfigs is a parsable slice of AdaptiveGroupConfig.
type AdaptiveGroupConfigs []*AdaptiveGroupConfig
