// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adaptivegroupconfig"
	"github.com/Wei-Shaw/sub2api/ent/adaptivegroupmembership"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// AdaptiveGroupConfigCreate is the builder for creating a AdaptiveGroupConfig entity.
type AdaptiveGroupConfigCreate struct {
	config
	mutation *AdaptiveGroupConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdaptiveGroupConfigCreate) SetCreatedAt(v time.Time) *AdaptiveGroupConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdaptiveGroupConfigCreate) SetNillableCreatedAt(v *time.Time) *AdaptiveGroupConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AdaptiveGroupConfigCreate) SetUpdatedAt(v time.Time) *AdaptiveGroupConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AdaptiveGroupConfigCreate) SetNillableUpdatedAt(v *time.Time) *AdaptiveGroupConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetParentGroupID sets the "parent_group_id" field.
func (_c *AdaptiveGroupConfigCreate) SetParentGroupID(v int64) *AdaptiveGroupConfigCreate {
	_c.mutation.SetParentGroupID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *AdaptiveGroupConfigCreate) SetEnabled(v bool) *AdaptiveGroupConfigCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *AdaptiveGroupConfigCreate) SetNillableEnabled(v *bool) *AdaptiveGroupConfigCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetConfigGeneration sets the "config_generation" field.
func (_c *AdaptiveGroupConfigCreate) SetConfigGeneration(v int64) *AdaptiveGroupConfigCreate {
	_c.mutation.SetConfigGeneration(v)
	return _c
}

// SetNillableConfigGeneration sets the "config_generation" field if the given value is not nil.
func (_c *AdaptiveGroupConfigCreate) SetNillableConfigGeneration(v *int64) *AdaptiveGroupConfigCreate {
	if v != nil {
		_c.SetConfigGeneration(*v)
	}
	return _c
}

// SetParentGroup sets the "parent_group" edge to the Group entity.
func (_c *AdaptiveGroupConfigCreate) SetParentGroup(v *Group) *AdaptiveGroupConfigCreate {
	return _c.SetParentGroupID(v.ID)
}

// AddMemberIDs adds the "members" edge to the AdaptiveGroupMembership entity by IDs.
func (_c *AdaptiveGroupConfigCreate) AddMemberIDs(ids ...int64) *AdaptiveGroupConfigCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the AdaptiveGroupMembership entity.
func (_c *AdaptiveGroupConfigCreate) AddMembers(v ...*AdaptiveGroupMembership) *AdaptiveGroupConfigCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// Mutation returns the AdaptiveGroupConfigMutation object of the builder.
func (_c *AdaptiveGroupConfigCreate) Mutation() *AdaptiveGroupConfigMutation {
	return _c.mutation
}

// Save creates the AdaptiveGroupConfig in the database.
func (_c *AdaptiveGroupConfigCreate) Save(ctx context.Context) (*AdaptiveGroupConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdaptiveGroupConfigCreate) SaveX(ctx context.Context) *AdaptiveGroupConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdaptiveGroupConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdaptiveGroupConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdaptiveGroupConfigCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := adaptivegroupconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := adaptivegroupconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := adaptivegroupconfig.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.ConfigGeneration(); !ok {
		v := adaptivegroupconfig.DefaultConfigGeneration
		_c.mutation.SetConfigGeneration(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdaptiveGroupConfigCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdaptiveGroupConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AdaptiveGroupConfig.updated_at"`)}
	}
	if _, ok := _c.mutation.ParentGroupID(); !ok {
		return &ValidationError{Name: "parent_group_id", err: errors.New(`ent: missing required field "AdaptiveGroupConfig.parent_group_id"`)}
	}
	if v, ok := _c.mutation.ParentGroupID(); ok {
		if err := adaptivegroupconfig.ParentGroupIDValidator(v); err != nil {
			return &ValidationError{Name: "parent_group_id", err: fmt.Errorf(`ent: validator failed for field "AdaptiveGroupConfig.parent_group_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "AdaptiveGroupConfig.enabled"`)}
	}
	if _, ok := _c.mutation.ConfigGeneration(); !ok {
		return &ValidationError{Name: "config_generation", err: errors.New(`ent: missing required field "AdaptiveGroupConfig.config_generation"`)}
	}
	if v, ok := _c.mutation.ConfigGeneration(); ok {
		if err := adaptivegroupconfig.ConfigGenerationValidator(v); err != nil {
			return &ValidationError{Name: "config_generation", err: fmt.Errorf(`ent: validator failed for field "AdaptiveGroupConfig.config_generation": %w`, err)}
		}
	}
	if len(_c.mutation.ParentGroupIDs()) == 0 {
		return &ValidationError{Name: "parent_group", err: errors.New(`ent: missing required edge "AdaptiveGroupConfig.parent_group"`)}
	}
	return nil
}

func (_c *AdaptiveGroupConfigCreate) sqlSave(ctx context.Context) (*AdaptiveGroupConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdaptiveGroupConfigCreate) createSpec() (*AdaptiveGroupConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &AdaptiveGroupConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adaptivegroupconfig.Table, sqlgraph.NewFieldSpec(adaptivegroupconfig.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adaptivegroupconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(adaptivegroupconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(adaptivegroupconfig.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.ConfigGeneration(); ok {
		_spec.SetField(adaptivegroupconfig.FieldConfigGeneration, field.TypeInt64, value)
		_node.ConfigGeneration = value
	}
	if nodes := _c.mutation.ParentGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adaptivegroupconfig.ParentGroupTable,
			Columns: []string{adaptivegroupconfig.ParentGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentGroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   adaptivegroupconfig.MembersTable,
			Columns: []string{adaptivegroupconfig.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adaptivegroupmembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdaptiveGroupConfig.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdaptiveGroupConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AdaptiveGroupConfigCreate) OnConflict(opts ...sql.ConflictOption) *AdaptiveGroupConfigUpsertOne {
	_c.conflict = opts
	return &AdaptiveGroupConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdaptiveGroupConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdaptiveGroupConfigCreate) OnConflictColumns(columns ...string) *AdaptiveGroupConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdaptiveGroupConfigUpsertOne{
		create: _c,
	}
}

type (
	// AdaptiveGroupConfigUpsertOne is the builder for "upsert"-ing
	//  one AdaptiveGroupConfig node.
	AdaptiveGroupConfigUpsertOne struct {
		create *AdaptiveGroupConfigCreate
	}

	// AdaptiveGroupConfigUpsert is the "OnConflict" setter.
	AdaptiveGroupConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AdaptiveGroupConfigUpsert) SetUpdatedAt(v time.Time) *AdaptiveGroupConfigUpsert {
	u.Set(adaptivegroupconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdaptiveGroupConfigUpsert) UpdateUpdatedAt() *AdaptiveGroupConfigUpsert {
	u.SetExcluded(adaptivegroupconfig.FieldUpdatedAt)
	return u
}

// SetParentGroupID sets the "parent_group_id" field.
func (u *AdaptiveGroupConfigUpsert) SetParentGroupID(v int64) *AdaptiveGroupConfigUpsert {
	u.Set(adaptivegroupconfig.FieldParentGroupID, v)
	return u
}

// UpdateParentGroupID sets the "parent_group_id" field to the value that was provided on create.
func (u *AdaptiveGroupConfigUpsert) UpdateParentGroupID() *AdaptiveGroupConfigUpsert {
	u.SetExcluded(adaptivegroupconfig.FieldParentGroupID)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *AdaptiveGroupConfigUpsert) SetEnabled(v bool) *AdaptiveGroupConfigUpsert {
	u.Set(adaptivegroupconfig.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AdaptiveGroupConfigUpsert) UpdateEnabled() *AdaptiveGroupConfigUpsert {
	u.SetExcluded(adaptivegroupconfig.FieldEnabled)
	return u
}

// SetConfigGeneration sets the "config_generation" field.
func (u *AdaptiveGroupConfigUpsert) SetConfigGeneration(v int64) *AdaptiveGroupConfigUpsert {
	u.Set(adaptivegroupconfig.FieldConfigGeneration, v)
	return u
}

// UpdateConfigGeneration sets the "config_generation" field to the value that was provided on create.
func (u *AdaptiveGroupConfigUpsert) UpdateConfigGeneration() *AdaptiveGroupConfigUpsert {
	u.SetExcluded(adaptivegroupconfig.FieldConfigGeneration)
	return u
}

// AddConfigGeneration adds v to the "config_generation" field.
func (u *AdaptiveGroupConfigUpsert) AddConfigGeneration(v int64) *AdaptiveGroupConfigUpsert {
	u.Add(adaptivegroupconfig.FieldConfigGeneration, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AdaptiveGroupConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdaptiveGroupConfigUpsertOne) UpdateNewValues() *AdaptiveGroupConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(adaptivegroupconfig.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdaptiveGroupConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AdaptiveGroupConfigUpsertOne) Ignore() *AdaptiveGroupConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdaptiveGroupConfigUpsertOne) DoNothing() *AdaptiveGroupConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdaptiveGroupConfigCreate.OnConflict
// documentation for more info.
func (u *AdaptiveGroupConfigUpsertOne) Update(set func(*AdaptiveGroupConfigUpsert)) *AdaptiveGroupConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdaptiveGroupConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AdaptiveGroupConfigUpsertOne) SetUpdatedAt(v time.Time) *AdaptiveGroupConfigUpsertOne {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdaptiveGroupConfigUpsertOne) UpdateUpdatedAt() *AdaptiveGroupConfigUpsertOne {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetParentGroupID sets the "parent_group_id" field.
func (u *AdaptiveGroupConfigUpsertOne) SetParentGroupID(v int64) *AdaptiveGroupConfigUpsertOne {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.SetParentGroupID(v)
	})
}

// UpdateParentGroupID sets the "parent_group_id" field to the value that was provided on create.
func (u *AdaptiveGroupConfigUpsertOne) UpdateParentGroupID() *AdaptiveGroupConfigUpsertOne {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.UpdateParentGroupID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *AdaptiveGroupConfigUpsertOne) SetEnabled(v bool) *AdaptiveGroupConfigUpsertOne {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AdaptiveGroupConfigUpsertOne) UpdateEnabled() *AdaptiveGroupConfigUpsertOne {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.UpdateEnabled()
	})
}

// SetConfigGeneration sets the "config_generation" field.
func (u *AdaptiveGroupConfigUpsertOne) SetConfigGeneration(v int64) *AdaptiveGroupConfigUpsertOne {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.SetConfigGeneration(v)
	})
}

// AddConfigGeneration adds v to the "config_generation" field.
func (u *AdaptiveGroupConfigUpsertOne) AddConfigGeneration(v int64) *AdaptiveGroupConfigUpsertOne {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.AddConfigGeneration(v)
	})
}

// UpdateConfigGeneration sets the "config_generation" field to the value that was provided on create.
func (u *AdaptiveGroupConfigUpsertOne) UpdateConfigGeneration() *AdaptiveGroupConfigUpsertOne {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.UpdateConfigGeneration()
	})
}

// Exec executes the query.
func (u *AdaptiveGroupConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdaptiveGroupConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdaptiveGroupConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AdaptiveGroupConfigUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AdaptiveGroupConfigUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AdaptiveGroupConfigCreateBulk is the builder for creating many AdaptiveGroupConfig entities in bulk.
type AdaptiveGroupConfigCreateBulk struct {
	config
	err      error
	builders []*AdaptiveGroupConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the AdaptiveGroupConfig entities in the database.
func (_c *AdaptiveGroupConfigCreateBulk) Save(ctx context.Context) ([]*AdaptiveGroupConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdaptiveGroupConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdaptiveGroupConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdaptiveGroupConfigCreateBulk) SaveX(ctx context.Context) []*AdaptiveGroupConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdaptiveGroupConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdaptiveGroupConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdaptiveGroupConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdaptiveGroupConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AdaptiveGroupConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *AdaptiveGroupConfigUpsertBulk {
	_c.conflict = opts
	return &AdaptiveGroupConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdaptiveGroupConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdaptiveGroupConfigCreateBulk) OnConflictColumns(columns ...string) *AdaptiveGroupConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdaptiveGroupConfigUpsertBulk{
		create: _c,
	}
}

// AdaptiveGroupConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of AdaptiveGroupConfig nodes.
type AdaptiveGroupConfigUpsertBulk struct {
	create *AdaptiveGroupConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AdaptiveGroupConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdaptiveGroupConfigUpsertBulk) UpdateNewValues() *AdaptiveGroupConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(adaptivegroupconfig.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdaptiveGroupConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AdaptiveGroupConfigUpsertBulk) Ignore() *AdaptiveGroupConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdaptiveGroupConfigUpsertBulk) DoNothing() *AdaptiveGroupConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdaptiveGroupConfigCreateBulk.OnConflict
// documentation for more info.
func (u *AdaptiveGroupConfigUpsertBulk) Update(set func(*AdaptiveGroupConfigUpsert)) *AdaptiveGroupConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdaptiveGroupConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AdaptiveGroupConfigUpsertBulk) SetUpdatedAt(v time.Time) *AdaptiveGroupConfigUpsertBulk {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdaptiveGroupConfigUpsertBulk) UpdateUpdatedAt() *AdaptiveGroupConfigUpsertBulk {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetParentGroupID sets the "parent_group_id" field.
func (u *AdaptiveGroupConfigUpsertBulk) SetParentGroupID(v int64) *AdaptiveGroupConfigUpsertBulk {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.SetParentGroupID(v)
	})
}

// UpdateParentGroupID sets the "parent_group_id" field to the value that was provided on create.
func (u *AdaptiveGroupConfigUpsertBulk) UpdateParentGroupID() *AdaptiveGroupConfigUpsertBulk {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.UpdateParentGroupID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *AdaptiveGroupConfigUpsertBulk) SetEnabled(v bool) *AdaptiveGroupConfigUpsertBulk {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AdaptiveGroupConfigUpsertBulk) UpdateEnabled() *AdaptiveGroupConfigUpsertBulk {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.UpdateEnabled()
	})
}

// SetConfigGeneration sets the "config_generation" field.
func (u *AdaptiveGroupConfigUpsertBulk) SetConfigGeneration(v int64) *AdaptiveGroupConfigUpsertBulk {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.SetConfigGeneration(v)
	})
}

// AddConfigGeneration adds v to the "config_generation" field.
func (u *AdaptiveGroupConfigUpsertBulk) AddConfigGeneration(v int64) *AdaptiveGroupConfigUpsertBulk {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.AddConfigGeneration(v)
	})
}

// UpdateConfigGeneration sets the "config_generation" field to the value that was provided on create.
func (u *AdaptiveGroupConfigUpsertBulk) UpdateConfigGeneration() *AdaptiveGroupConfigUpsertBulk {
	return u.Update(func(s *AdaptiveGroupConfigUpsert) {
		s.UpdateConfigGeneration()
	})
}

// Exec executes the query.
func (u *AdaptiveGroupConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AdaptiveGroupConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdaptiveGroupConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdaptiveGroupConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
