// Code generated by ent, DO NOT EDIT.

package adaptivegroupmembership

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the adaptivegroupmembership type in the database.
	Label = "adaptive_group_membership"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldConfigID holds the string denoting the config_id field in the database.
	FieldConfigID = "config_id"
	// FieldLeafGroupID holds the string denoting the leaf_group_id field in the database.
	FieldLeafGroupID = "leaf_group_id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// EdgeConfig holds the string denoting the config edge name in mutations.
	EdgeConfig = "config"
	// EdgeLeafGroup holds the string denoting the leaf_group edge name in mutations.
	EdgeLeafGroup = "leaf_group"
	// Table holds the table name of the adaptivegroupmembership in the database.
	Table = "adaptive_group_memberships"
	// ConfigTable is the table that holds the config relation/edge.
	ConfigTable = "adaptive_group_memberships"
	// ConfigInverseTable is the table name for the AdaptiveGroupConfig entity.
	// It exists in this package in order to avoid circular dependency with the "adaptivegroupconfig" package.
	ConfigInverseTable = "adaptive_group_configs"
	// ConfigColumn is the table column denoting the config relation/edge.
	ConfigColumn = "config_id"
	// LeafGroupTable is the table that holds the leaf_group relation/edge.
	LeafGroupTable = "adaptive_group_memberships"
	// LeafGroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	LeafGroupInverseTable = "groups"
	// LeafGroupColumn is the table column denoting the leaf_group relation/edge.
	LeafGroupColumn = "leaf_group_id"
)

// Columns holds all SQL columns for adaptivegroupmembership fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldConfigID,
	FieldLeafGroupID,
	FieldEnabled,
	FieldSortOrder,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ConfigIDValidator is a validator for the "config_id" field. It is called by the builders before save.
	ConfigIDValidator func(int64) error
	// LeafGroupIDValidator is a validator for the "leaf_group_id" field. It is called by the builders before save.
	LeafGroupIDValidator func(int64) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
)

// OrderOption defines the ordering options for the AdaptiveGroupMembership queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByConfigID orders the results by the config_id field.
func ByConfigID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigID, opts...).ToFunc()
}

// ByLeafGroupID orders the results by the leaf_group_id field.
func ByLeafGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeafGroupID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByConfigField orders the results by config field.
func ByConfigField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConfigStep(), sql.OrderByField(field, opts...))
	}
}

// ByLeafGroupField orders the results by leaf_group field.
func ByLeafGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLeafGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newConfigStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConfigInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ConfigTable, ConfigColumn),
	)
}
func newLeafGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LeafGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, LeafGroupTable, LeafGroupColumn),
	)
}
