// Code generated by ent, DO NOT EDIT.

package adaptivegroupmembership

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldEQ(FieldUpdatedAt, v))
}

// ConfigID applies equality check predicate on the "config_id" field. It's identical to ConfigIDEQ.
func ConfigID(v int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldEQ(FieldConfigID, v))
}

// LeafGroupID applies equality check predicate on the "leaf_group_id" field. It's identical to LeafGroupIDEQ.
func LeafGroupID(v int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldEQ(FieldLeafGroupID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldEQ(FieldEnabled, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldLTE(FieldUpdatedAt, v))
}

// ConfigIDEQ applies the EQ predicate on the "config_id" field.
func ConfigIDEQ(v int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldEQ(FieldConfigID, v))
}

// ConfigIDNEQ applies the NEQ predicate on the "config_id" field.
func ConfigIDNEQ(v int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldNEQ(FieldConfigID, v))
}

// ConfigIDIn applies the In predicate on the "config_id" field.
func ConfigIDIn(vs ...int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldIn(FieldConfigID, vs...))
}

// ConfigIDNotIn applies the NotIn predicate on the "config_id" field.
func ConfigIDNotIn(vs ...int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldNotIn(FieldConfigID, vs...))
}

// LeafGroupIDEQ applies the EQ predicate on the "leaf_group_id" field.
func LeafGroupIDEQ(v int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldEQ(FieldLeafGroupID, v))
}

// LeafGroupIDNEQ applies the NEQ predicate on the "leaf_group_id" field.
func LeafGroupIDNEQ(v int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldNEQ(FieldLeafGroupID, v))
}

// LeafGroupIDIn applies the In predicate on the "leaf_group_id" field.
func LeafGroupIDIn(vs ...int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldIn(FieldLeafGroupID, vs...))
}

// LeafGroupIDNotIn applies the NotIn predicate on the "leaf_group_id" field.
func LeafGroupIDNotIn(vs ...int64) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldNotIn(FieldLeafGroupID, vs...))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldNEQ(FieldEnabled, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.FieldLTE(FieldSortOrder, v))
}

// HasConfig applies the HasEdge predicate on the "config" edge.
func HasConfig() predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ConfigTable, ConfigColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConfigWith applies the HasEdge predicate on the "config" edge with a given conditions (other predicates).
func HasConfigWith(preds ...predicate.AdaptiveGroupConfig) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(func(s *sql.Selector) {
		step := newConfigStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLeafGroup applies the HasEdge predicate on the "leaf_group" edge.
func HasLeafGroup() predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, LeafGroupTable, LeafGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLeafGroupWith applies the HasEdge predicate on the "leaf_group" edge with a given conditions (other predicates).
func HasLeafGroupWith(preds ...predicate.Group) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(func(s *sql.Selector) {
		step := newLeafGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdaptiveGroupMembership) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdaptiveGroupMembership) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdaptiveGroupMembership) predicate.AdaptiveGroupMembership {
	return predicate.AdaptiveGroupMembership(sql.NotPredicates(p))
}
